### PR TITLE
Added tracking and line spacing

### PR DESCRIPTION
**Pull request by mauriceschenk**
This PR addresses #47.

### CODE REVIEW

**Review by brendanlensink — CHANGES_REQUESTED** [review]
Thanks for the contribution! 

These changes look great, but I think they should belong in `FontStyle`, rather than `NiceTextStyle`, with the other font related options like size and weight.

**Comment by mauriceschenk** [comment]
Is `lineSpacing` a font related attribute? We have `lineLimit` in `NiceTextStyle`, so wouldn't it make more sense then to keep it here and only move `tracking`?

**Comment by brendanlensink** [comment]
Yes, you're absolutely right. I had convinced myself they should stay together but that doesn't make much sense in hindsight 😅 

Lets split them off so `lineSpacing` lives in `NiceTextStyle` and `tracking` lives in `FontStyle`

**Review by brendanlensink — APPROVED** [review]
🚀 

Don't forget to update the changelog before merging!

**Pull request merged**
